# Generated by Django 4.0.1 on 2022-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0003_alter_user_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birthdate',
            field=models.DateField(),
        ),
    ]
